info:
  application:
    name: @project.name@
    description: @project.description@

spring:
  application:
    name: @project.name@
    version: @project.version@

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/app_migrations.xml

  messages:
    basename: i18n/messages
    encoding: UTF-8

basic-authentication:
  manager:
    username: manager@gmail.com
    password: manager

  student:
    username: student1@gmail.com
    password: student1

course:
  reminder:
    cron: "0 0 9 * * *"
    daysBefore: 1

management:
  endpoints:
    web:
      exposure:
        include: caches,health,info,loggers

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

springdoc:
  override-with-generic-response: false
  show-actuator: true