spring:
  config:
    import: secrets-local.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: test
    password: test

  jpa:
    show-sql: true

logging:
  level:
    liquibase: info
    org:
      springframework:
        cache: trace

mail:
  from: hello@demomailtrap.co
  user: smtp@mailtrap.io
  password:
  host: live.smtp.mailtrap.io
  port: 587
  protocol: smtp
  auth: true
  start-tls-enable: true

approuter:
  url:

xsuaa:
  client-id:
  client-secret:
  token-url:

application:
  dependencies:
    -

sap:
  security:
    services:
      xsuaa:
        xsappname: xsapp!t0815
        uaadomain: localhost
        clientid: sb-clientId!t0815
        clientsecret: pwd
        url: http://localhost
        plan: application

service-manager:
  client-id: sb-1e5e36d7-09da-4416-b97e-bccdf8d3e889!b413607|service-manager!b1476
  client-secret: 2cfb2233-0900-4a1e-ab54-cce9d53b0cc9$MtRVpACO1AwpU0mckpdJwZq7VuiLycKNB7hjhTVxiwo=
  token-url: https://4a826b62trial.authentication.us10.hana.ondemand.com
  url: https://service-manager.cfapps.us10.hana.ondemand.com

default-tenant: trial
