application:
  name: lms
  service-dependencies:
    -
  uri: http://localhost:8080

spring:
  config:
    import: secrets-local.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: test
    password: test

  jpa:
    show-sql: true

logging:
  level:
    liquibase: info
    org:
      springframework:
        cache: trace

mail:
  from: hello@demomailtrap.co
  user: smtp@mailtrap.io
  password:
  host: live.smtp.mailtrap.io
  port: 587
  protocol: smtp
  auth: true
  start-tls-enable: true

btp:
  services:
    xsuaa:
      xsappname: xsapp!t0815
      uaadomain: localhost
      client-id: sb-clientId!t0815
      clients-secret: pwd
      token-url: http://localhost