application:
  service-dependencies:
    - ${vcap.services.lms-destination-service.credentials.xsappname}

spring:
  datasource:
    url: ${vcap.services.lms-hana-schema.credentials.url}
    username: ${vcap.services.lms-hana-schema.credentials.user}
    password: ${vcap.services.lms-hana-schema.credentials.password}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${vcap.services.lms-xsuaa.credentials.url}/oauth/token

mail:
  from: ${vcap.services.lms-user-service.credentials.from}
  user: ${vcap.services.lms-user-service.credentials.user}
  password: ${vcap.services.lms-user-service.credentials.password}
  host: ${vcap.services.lms-user-service.credentials.host}
  port: ${vcap.services.lms-user-service.credentials.port}
  protocol: ${vcap.services.lms-user-service.credentials.protocol}
  auth: ${vcap.services.lms-user-service.credentials.auth}
  start-tls-enable: ${vcap.services.lms-user-service.credentials.startTls}

multitenancy:
  default-tenant: 724669da-9da4-479b-a040-cbee69ac27d1

sap:
  security:
    services:
      destination-service:
        uri: ${vcap.services.lms-destination-service.credentials.uri}
        token-url: ${vcap.services.lms-destination-service.credentials.url}
        client_id: ${vcap.services.lms-destination-service.credentials.clientid}
        client_secret: ${vcap.services.lms-destination-service.credentials.clientsecret}

      feature-flags:
        uri: ${vcap.services.lms-feature-flags.credentials.uri}
        username: ${vcap.services.lms-feature-flags.credentials.username}
        password: ${vcap.services.lms-feature-flags.credentials.password}

      service-manager:
        client-id: ${vcap.services.service-manager.credentials.clientid}
        client-secret: ${vcap.services.service-manager.credentials.clientsecret}
        token-url: ${vcap.services.service-manager.credentials.url}
        url: ${vcap.services.service-manager.credentials.sm_url}

      xsuaa:
        xsappname: ${vcap.services.lms-xsuaa.credentials.xsappname}
        uaadomain: ${vcap.services.lms-xsuaa.credentials.uaadomain}
        clientid: ${vcap.services.lms-xsuaa.credentials.clientid}
        clientsecret: ${vcap.services.lms-xsuaa.credentials.clientsecret}
        url: ${vcap.services.lms-xsuaa.credentials.url}