spring:
  config:
    import: secrets-local.yaml

  h2:
    console:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true

logging:
  level:
    liquibase: info
    org:
      springframework:
        cache: trace