application:
  service-dependencies:
    -
datasource:
  url: jdbc:postgresql://localhost:5432/lms
  username: test
  password: test

spring:
  config:
    import: secrets-local.yaml

  jpa:
    show-sql: true

logging:
  level:
    liquibase: info
    org:
      springframework:
        cache: trace

mail:
  from: hello@demomailtrap.co
  user: smtp@mailtrap.io
  password:
  host: live.smtp.mailtrap.io
  port: 587
  protocol: smtp
  auth: true
  start-tls-enable: true

multitenancy:
  default-tenant: public
  default-schema: public

sap:
  security:
    services:
      service-manager:
        client-id:
        client-secret:
        token-url:
        url:

      xsuaa:
        xsappname: xsapp!t0815
        uaadomain: localhost
        clientid: sb-clientId!t0815
        clientsecret: pwd
        url: http://localhost
        plan: application